server:
  port: 80

#服务别名----注册zookeeper到注册中心名称
spring:
  application:
    name: cloud-provider-payment
  cloud:
    zookeeper:
      connect-string: 192.168.202.1:8888 # Zookeeper注册中心ip地址 端口还
        # 192.168.202.133:8888 Linux上Zookeeper注册中心的地址;
      # 192.168.202.1:8888 Windows上Zookeeper注册中心的地址;
